# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: zyno-io.sp2p
PackageVersion: 0.6.1
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: sp2p.exe
  PortableCommandAlias: sp2p
ReleaseDate: 2026-09-27
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/zyno-io/sp2p/releases/download/v0.6.1/sp2p_windows_amd64.zip
  InstallerSha256: B3FBE0696AB302E208096F148B99EAE4DF1602C736DF67DCEF5340C8A9C3F0FB
- Architecture: arm64
  InstallerUrl: https://github.com/zyno-io/sp2p/releases/download/v0.6.1/sp2p_windows_arm64.zip
  InstallerSha256: E1AB41CA4907977723C84596831ED116526CEE2B506F44FF02A5E6EFE417AFB1
ManifestType: installer
ManifestVersion: 1.12.0
